### ISSUE TITLE
USER STORY: Product Basket

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#10]
As a **user** I need **a basket** in order to **to store my products for a future purchase**

## ACCEPTANCE CRITERIAS:
Added products appear with the following info: 
- [x] Product image
- [x] Product name
- [x] Product unit price
- [x] Product quantity
- [x] Product total price

The basket must show the following info
- [x] Total basket price
- [x] Delivery price (10% of total basket price)
- [x] The grand total price (delivery +basket total price)
- [x] Have a checkout button to access the payment step
- [x] Have back to products button to keep shopping

## TASKS:
- [x] Create a Basket app
- [x] Create a basket view
- [x] Create a basket template
- [x] Create basket urls
- [x] Add Product image in html
- [x] Add Product name in html
- [x] Add Product unit price in html
- [x] Add Product quantity in html
- [x] Add Product total price in html
- [x] Add Total basket price
- [x] Add Delivery price (10% of total basket price)
- [x] Add The grand total price (delivery +basket total price)
- [x] Add checkout button to access the payment step
- [x] Add back to products button to keep shopping
