### ISSUE TITLE
USER STORY: Basket product quantity buttons

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#11]
As a **user** I need **quantity buttons** in order to **add or remove products easily**

## ACCEPTANCE CRITERIAS:
- [x] Have a + button
- [x] Have a - button
- [x] Have number of items display
- [x] impossible to go below 0
- [x] 0 items = delete product
- [x] number of items change accordingly
- [x] Change number of items directly by typing number of items.
- [x] Only integers can be inserted
- [x] Price change accordingly with quantity

## TASKS:
- [x] Create + and - buttons in product details HTML
- [x] Create Javascript
