### ISSUE TITLE
USER STORY: Index html

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#12]
As a **user** I need **landing page** in order to **understand at once what is the site**

## ACCEPTANCE CRITERIAS:
- [x] hero Image
- [x] Shop now button that redirects to all products
- [x] 4 reasons to buy from us 

## TASKS:
- [x] Add hero image
- [x] Add shop now button with link to all products
- [x] Add reason to buy with us (Fast delivery, Exclusive dealers, Tested products, Professional tools only)
