### ISSUE TITLE
USER STORY: Base.html

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#13]
As a **developper** I need **to create a base,html page** in order to **build my site upon**

## ACCEPTANCE CRITERIAS:
- [x]  A top banner section
- [x] A footer section

## TASKS:
- [x] build top banner section
- [x] build footer section
