### ISSUE TITLE
USER STORY: Top banner

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#14]
As a **user** I need **to a top banner** in order to **navigate the site easily**

## ACCEPTANCE CRITERIAS:
- [x] banner visible throughout all site
- [x]  banner collapses for small screens
- [x] Banner contains back home link logo
- [x] Banner contains search
- [x] Banner contains account button
- [x] Banner contains Basket button

## TASKS:
- [x] Add logo wit link to index.html
- [x] Add search field
- [x] Add Account logo
- [x] Add Basket logo
- [x] Style with CSS
