### ISSUE TITLE
USER STORY: Mobile top banner html

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#15]
As a **user** I need **specific mobile top banner** in order to **navigate easily on small screens**

## ACCEPTANCE CRITERIAS:
- [x] Burger menu for categories
- [x] clickable logo for search
- [x] search field appears when search is clicked
- [x] html used only on screens lower than 992px wide

## TASKS:
- [x] Integrate a collapsable burger menu
- [x] Search field on click
