### ISSUE TITLE
USER STORY: Footer

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#16]
As a **user** I need **a footer** in order to **to access important general information**

## ACCEPTANCE CRITERIAS:
- [x] visible throughout website
- [x] Responsive
- [x] Has 4 columns (le patiiser info, link to brands websites, legal, Social Media)
- [x] Has a newsletter link

## TASKS:
- [x] Build a bootstrap structure for responsiveness 

Add le patissier column with 
- [x] Address
- [x] email
- [x] telephone number
- [x] Link to contact us page

Add brands column with 
- [x] Link to Mafter website
- [x] Link to Hendi website
- [x] Link to Mallard ferreiere website
- [x] Link to De Buyer website

Add legal column with 
- [x] Link to terms and conditions page
- [x] Link to garanty page
- [x] Link to legal statement page
- [x] Link to privacy policy

Add follow us column with 
- [x] Facebook page link
- [x] twitter link
- [x] instagram link
- [x] youtube link
