### ISSUE TITLE
USER STORY: Legal Statement.html

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#17]
As a **user** I need **a legal statement page** in order to **see the company legal registration**

## ACCEPTANCE CRITERIAS:
- [x] 1 pager
- [x] all legal information 

## TASKS:
- [x] Build the html page
- [x] build the view
- [x] build url
- [x] link it to footer
