### ISSUE TITLE
USER STORY: Terms and conditions html

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#18]
As a **user** I need **a terms and condition page** in order to **see the company rules**

## ACCEPTANCE CRITERIAS:
- [x] 1 pager
- [x] all terms and condition clearly defined

## TASKS:
- [x] Build the html page
- [x] build the view
- [x] build url
- [x] link it to footer
