### ISSUE TITLE
USER STORY: Guaranty html

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#19]
As a **user** I need **a guarantee page** in order to **see the company's seriousness**

## ACCEPTANCE CRITERIAS:
- [x] 1 pager
- [x] all guaranty information 

## TASKS:
- [x] Build the html page
- [x] build the view
- [x] build url
- [x] link it to footer
