### ISSUE TITLE
USER STORY: Edit Product Button

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#2]
As an  **Adim** I need **an edit button on products** in order to **access the edit product menu**

## ACCEPTANCE CRITERIAS:
- [x] The Button needs to appear on product details
- [x] The button needs to appear only for Admins

## TASKS:
- [x] Add button in Product details page
- [x] Create an if statement so that only Admins can see it
- [x] Button needs to be a link to update product page
