### ISSUE TITLE
USER STORY: Privacy Policy html

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#20]
As a **user** I need **privacy policy page** in order to **see what the company does with my data**

## ACCEPTANCE CRITERIAS:
- [x] 1 pager
- [x] all privacy policy statement 

## TASKS:
- [x] Build the html page
- [x] build the view
- [x] build url
- [x] link it to footer
