### ISSUE TITLE
USER STORY: Create a Newsletter app

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#21]
As a **developper** I need **a marketing app** in order to **manage the news letter**

## ACCEPTANCE CRITERIAS:
- [x] App is seperated

## TASKS:
- [x] Create Marketing app in django
- [x] Add app to settings
