### ISSUE TITLE
UESER STORY: Favorite list

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#24]
As a **User** I need ** a favorite list ** in order to **find my favorite products in order to buys them faster**

## ACCEPTANCE CRITERIAS:
- [ ] Click on an icon to add product to list
- [ ] product appears in list
- [ ] list can be seen only by user

## TASKS:
- [ ] Create view
- [ ] Create html template
- [ ] Url
