### ISSUE TITLE
USER STORY: Delete product button

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#3]
As an **admin** I need **a delete button** in order to **delete products from the database**

## ACCEPTANCE CRITERIAS:
- [x] Only admins can see the button
- [x] The button appears on the product details page
- [x] The button appears on the product card of the All products page
- [x] The button deletes the product from database
- [x] The button deletes product from ALL pages (basket and Checkout page included )

## TASKS:
- [x] Add button to product detail page
- [x] Add button to  product card in all product page
- [x] Add if statement for product card and product detail page
- [x] Create class view class to delete product

**Comment by 0xScratch** [comment]
You be doing this yourself or need some help?
