### ISSUE TITLE
USER STORY: Edit product button

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#5]
As an **admin** I need **an edit button** in order to **edit products details**

## ACCEPTANCE CRITERIAS:
- [x] Only admins can see the button
- [x] The button appears on the product details page
- [x] The button appears on the product card of the All products page
- [x] The button redirects the admin to the edit product page

## TASKS:
- [x] Add button to product detail page
- [x] Add button to product card in all product page
- [x] Add if statement for product card and product detail page html
