### ISSUE TITLE
USER STORY: Product Card

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#6]
As a **user** I need **a product card** in order to **compare the products main details easily**

## ACCEPTANCE CRITERIAS:
- [x] Card product must be unique (seen only once)
- [x] Card product must show the product image or a default one
- [x] Card product must show the product price
- [x] Card product must show the product discount
- [x] Card product must show the product discounted price
- [x] Card product must show the product Brand
- [x] Card product must show whether the product is available or not

## TASKS:
- [x] Create a product view
- [x] Create a all prodct template
- [x] Create a loop to iterate through all products
- [x] Create a bootstrap card to show each product in the loop
- [x] Add the product image
- [x] Add the product name
- [x] Add the product brand
- [x] Add the discount
- [x] Add the product price and discounted price
