### ISSUE TITLE
UESER STORY: Product details page

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#7]
As a **user** I need **a product detail page** in order to **have more information and add product to basket**

## ACCEPTANCE CRITERIAS:
- [x] Product details page must show the product image or a default one
- [x] Product details page must show the product price
- [x] Product details page must show the product discount
- [x] Product details page must show the product discounted price
- [x] Product details page must show the product Brand as a link to all products of the brand
- [x] Product details page must show the product description
- [x] Product details page must show if the product is in stock
- [x] Product details page must have a review section
- [x] Product details page must have a button to choose quantity to buy
- [x] Product details page must have button to add to basket

## TASKS:
- [x] Create a product details view
- [x] Create a product detail template
- [x] Add the product image
- [x] Add the product name
- [x] Add the product brand
- [x] Add the product description
- [x] Add the discount
- [x] Add the product price and discounted price.
- [x] Add the review section 
- [x] Add the quantity buttons
- [x] Add the basket button
