### ISSUE TITLE
USER STORY: Newsletter button

### ISSUE THREAD

**Issue by LudovicLeGuen** [LudovicLeGuen/le_patissier#8]
As a **user** I need **a Newsletter button** in order to ** access the subscribe page**

## ACCEPTANCE CRITERIAS:
- [x] Button appears on all pages
- [x] Button is in the footer
- [x] Button redirects to Newsletter suscription page

## TASKS:
- [x] Create button in footer
- [x] Add link to the newsletter subscription page
